#!/bin/bash
# 🚀 Configuration Meshy.ai pour génération photoréaliste

echo "🎨 Configuration Meshy.ai"
echo "========================"
echo ""
echo "Pour obtenir un modèle photoréaliste, vous devez:"
echo ""
echo "1️⃣  Créer un compte sur https://www.meshy.ai/"
echo "    - Inscription gratuite"
echo "    - API key disponible dans le dashboard"
echo ""
echo "2️⃣  Exporter votre clé API:"
echo "    export MESHY_API_KEY='votre_cle_ici'"
echo ""
echo "3️⃣  Lancer l'API Meshy:"
echo "    python3 /home/belikan/Isol/Kibalone-Studio/meshy_api.py &"
echo ""
echo "4️⃣  Ouvrir Kibalone Studio:"
echo "    http://localhost:8080"
echo ""
echo "5️⃣  Taper un prompt comme:"
echo "    'guerrier futuriste avec armure détaillée'"
echo ""
echo "Le système essaiera automatiquement:"
echo "  1. Meshy.ai (photoréaliste) si configuré"
echo "  2. TripoSR local si disponible"
echo "  3. Génération procédurale améliorée (fallback)"
echo ""
echo "💡 Avantages Meshy.ai:"
echo "   ✅ Photoréalisme maximal"
echo "   ✅ Textures PBR"
echo "   ✅ Topologie propre"
echo "   ✅ Export GLB/FBX"
echo "   ✅ Pas besoin de GPU local"
echo ""
echo "🔥 Test rapide sans API key:"
echo "   Le système utilisera la génération procédurale améliorée"
echo ""
